### ISSUE TITLE
Documentation link broken

### ISSUE THREAD

**Issue by connor11528** [ezra-obiwale/laraquick#10]
Looks like an awesome project! The link for the documentation is currently broken

![screen shot 2018-07-07 at 10 11 50 pm](https://user-images.githubusercontent.com/3578908/42417032-e5c69b82-8232-11e8-9d73-a9f19d8a76f3.png)

**Comment by ezra-obiwale** [comment]
@connor11528 Thanks for the catch. Fixed it.

**Comment by connor11528** [comment]
Thanks!

https://laraquick.readme.io/docs
