### ISSUE TITLE
$item results in an undefined variable exception.

### ISSUE THREAD

**Issue by Mozartted** [ezra-obiwale/laraquick#11]
https://github.com/ezra-obiwale/laraquick/blob/dbf1ee194b01b215f44493802c9b4697672f742f/src/Controllers/Traits/Crud/Store.php#L107

**Comment by ezra-obiwale** [comment]
Please provide more information by answering the following:

- What were you trying to achieve?
- Which method did you call?
- At what point did you get an error?
- What was the error you got?

Thank you
